### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by Zireael** [mayflower/postgraphile-audit-plugin#2]
Hi,
I'm getting error `Cannot find module 'tslib'`

```
Error: Cannot find module 'tslib'
Require stack:
- /usr/local/lib/node_modules/postgraphile-audit-plugin/node_modules/graphile-utils/node8plus/index.js
- /usr/local/lib/node_modules/postgraphile-audit-plugin/dist/index.js
- /usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js
- /usr/local/lib/node_modules/postgraphile/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postgraphile-audit-plugin/node_modules/graphile-utils/node8plus/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/postgraphile-audit-plugin/node_modules/graphile-utils/node8plus/index.js',
    '/usr/local/lib/node_modules/postgraphile-audit-plugin/dist/index.js',
    '/usr/local/lib/node_modules/postgraphile/build/postgraphile/cli.js',
    '/usr/local/lib/node_modules/postgraphile/cli.js'
  ]
}
internal/modules/cjs/loader.js:1023
  throw err;
  ^
```

**My dockerfile:**
```
FROM node:14-alpine

RUN npm install -g graphql
RUN npm install -g postgraphile
RUN npm install -g graphile-build

RUN npm install -g postgraphile-plugin-connection-filter

RUN npm install -g @graphile-contrib/pg-simplify-inflector
RUN npm install -g @graphile-contrib/pg-order-by-related
RUN npm install -g @graphile-contrib/pg-many-to-many
RUN npm install -g @graphile-contrib/pg-order-by-multi-column-index
RUN npm install -g @graphile/pg-pubsub

RUN npm install -g postgraphile-plugin-nested-mutations
RUN npm install -g postgraphile-audit-plugin

COPY .postgraphilerc.js .postgraphilerc.js

RUN npm cache clean --force
```

**.postgraphilerc.js**
```
const auditPlugin = {
  /**
   * name of the schema that contains the `get_audit_information` function
   */
  auditFunctionSchema: "study",

  /**
   * include "auditEvents" connection on audited types
   */
  auditEventConnection: true,

  /**
   * include "firstAuditEvent" and "lastAuditEvent" field on audited types
   */
  firstLastAuditEvent: true,

  /**
   * include "createdAt" and "lastModifiedAt" field on audited types
   */
  dateProps: true,

  /**
   * include "createdBy" and "lastModifiedBy" on audited types
   */
  nameProps: true,

  /**
   * define how "name" properties should be filled - either with the transaction's "user_name", or with a value from the "session_info" JSON
   * can be "user_name" or "session_info";
   */
  nameSource: "session_info",

  /**
   * if `nameSource` is "session_info", this describes the path to the username within the JSON
   * e.g. "{name}" or "{nested,user,name}" (see the #>> notation described in https://www.postgresql.org/docs/9.3/functions-json.html)
   */
  nameSessionInfoJsonPath: "{nested,name}",

  /**
   * if name cannot be filled (because it is null or undefined), fall back to this value
   */
  nameFallback: "unknown_user",
};

module.exports = {
  options: {
    graphileBuildOptions: {
      auditPlugin,
    },
  },
};
```

**docker-compose.yaml**

```
    command: [
        "postgraphile",
        "--plugins",
        "@graphile/pg-pubsub",
        "--append-plugins",
        "postgraphile-plugin-connection-filter,@graphile-contrib/pg-simplify-inflector,@graphile-contrib/pg-order-by-related,@graphile-contrib/pg-many-to-many,postgraphile-plugin-nested-mutations,postgraphile-audit-plugin",
        "--connection",
        "postgres://my_user:my_password@postgresql-master:5432/study_tracker",
        "--owner-connection",
        "postgres://postgres:postgres_password@postgresql-master:5432/study_tracker",
        "--host",
        "0.0.0.0",
        "--port",
        "5433",
        "--cors",
        "--schema",
        "study",
        "--watch",
        "--simple-collections",
        "both",
        "--enable-query-batching",
        "--no-ignore-rbac",
        "--dynamic-json",
        "--no-setof-functions-contain-nulls",
        "--subscriptions",
        "--simple-subscriptions",
        "--graphql",
        "/graphql",
        "--graphiql",
        "/graphiql",
        "--extended-errors",
        "errcode",
        "--enhance-graphiql",
      ]
```

**Comment by Zireael** [comment]
Folowing on the above, if I npm install tslib and pg, then I get the following error:

```
no entities found to add audit fields to
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: The first argument to makeExtendSchemaPlugin must be generated by the `gql` helper, or be an array of the same.
    at /usr/local/lib/node_modules/postgraphile-audit-plugin/node_modules/graphile-utils/node8plus/makeExtendSchemaPlugin.js:21:27
    at Array.reduce (<anonymous>)
    at /usr/local/lib/node_modules/postgraphile-audit-plugin/node_modules/graphile-utils/node8plus/makeExtendSchemaPlugin.js:19:55
    at SchemaBuilder.applyHooks (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:252:20)
    at SchemaBuilder.createBuild (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:307:24)
    at SchemaBuilder.buildSchema (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:321:26)
    at SchemaBuilder.watchSchema (/usr/local/lib/node_modules/postgraphile/node_modules/graphile-build/node8plus/SchemaBuilder.js:386:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.exports.watchPostGraphileSchema (/usr/local/lib/node_modules/postgraphile/node_modules/postgraphile-core/node8plus/index.js:252:5)
    at async createGqlSchema (/usr/local/lib/node_modules/postgraphile/build/postgraphile/postgraphile.js:67:21)  
```

**Comment by phryneas** [comment]
I'll take a look at that, it's quite possible that our build output requires `tslib` - I just never noticed as all our tests were done using TypeScript, which ships that library as part of it's core. Thanks for bringing that to our attention!

The second error you're getting should be because there is just nothing to audit, resulting in an empty schema extension - which the graphql parser doesn't like. Unfortunately, postgraphile offers no way to bail out of that, so it throws an error.
Currently, we're identifying auditable tables by looking for the property `audit_id` in the schema you specified in the options. Do you have any of those there?



> By the way, the pgmemento v0.7 doesn't seem to include function get_audit_information

Yes, `get_audit_information` is part of the `Setup.sql`.
The one we are shipping contains some workarounds for pre-0.7 though - with 0.7 out it should be possible to write that a lot more performant. I'll have to look into that.

```
# this will ask you for a target schema and then create the `AuditEvent` type and `get_audit_information` function.
psql -h host -p 5432 -U user -d database -f Setup.sql
```

**Comment by Zireael** [comment]
Thanks for your replies, i'll have a look to see if I've got something I can fix on my end. Few things I can clarify:

The pgmemento docs have now different name for the default audit_id column (`'pgmemento_audit_id'`):
https://github.com/pgMemento/pgMemento/wiki/Initialize-auditing
And I used their init function example and ended up with `'audit_trail_id'`, which get's put into the schema as `auditTrailId`, I guess (I'm using simple inflections plugin and few other goodies to beef up the stack). Could you add a key in .postgraphilerc.js to customise the name of the audit column the audit plugin expects?

Current [setup.sql](https://github.com/pgMemento/pgMemento/blob/master/src/SETUP.sql) doesn't seem to have `get_audit_information`, at least not in the source code. I was having trouble installing pgmemento in my docker environment, so just executed the *.sql files against my database and initialised by hand. There were few duds in their wiki that tripped me (names of some function parameters were wrong etc). It's possible pgmemento introduced breaking changes to their code since you've last looked without bumping into major version (and documenting them.). I looked at my list of functions in the schema and the `get_audit_information` wasn't there.

I've pasted you consents of my dockerfile and docker-compose - should be enough to see the build for yourselves.

What do you think?

**Comment by phryneas** [comment]
I'll take a look at the naming stuff. We're internally still using a very-soon-before-the-0.7-release snapshot, so I might have missed that renaming.

Meanwhile:
I'm not referring to pgMemento's `Setup.sql`, but to [our Setup.sql](https://github.com/mayflower/postgraphile-audit-plugin/blob/master/Setup.sql) ;)

**Comment by Zireael** [comment]
> Meanwhile:
> I'm not referring to pgMemento's `Setup.sql`, but to [our Setup.sql](https://github.com/mayflower/postgraphile-audit-plugin/blob/master/Setup.sql) ;)

Ah, then something went horribly wrong because that function didn't get added to my database Q.Q

**Comment by phryneas** [comment]
You have to execute that file by hand during the installation - we won't mess around in your database without your consent ;)

**Comment by phryneas** [comment]
But yeah, we could make that a lot more obvious in our readme.

**Comment by Zireael** [comment]
> But yeah, we could make that a lot more obvious in our readme.

I've missed that one then. Was the text glowing red with lots of emoticons sprinkled all over?
Thanks for the tip, I'll revisit more carefully now ^^

**Comment by phryneas** [comment]
Sorry this took a while, but I just released a version with support for `pgmemento_audit_id` (it's completely configurable) and an update `get_audit_information` function in `Setup.sql` which should be a lot more performant.
